name: g_manager_app
description: G manager app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  intl: ^0.17.0
  flash: ^3.0.5+1
  get_it: ^7.2.0
  auto_route: ^5.0.1
  photo_view: ^0.14.0
  collection: ^1.16.0
  flutter_svg: ^1.1.5
  google_fonts: 
  image_picker: ^0.8.6
  flutter_remix: ^0.0.3
  flutter_riverpod: ^2.0.2
  connectivity_plus: ^2.3.9
  freezed_annotation: ^2.1.0
  # modal_bottom_sheet: ^2.1.2
  flutter_screenutil: ^5.5.4
  shared_preferences: ^2.0.15
  google_maps_flutter: ^2.2.1
  cached_network_image: ^3.2.3
  syncfusion_flutter_charts: ^20.3.49
  flutter_keyboard_visibility: ^5.4.1
  webview_flutter: ^3.0.4
  webview_cookie_manager: ^2.0.6
  flutter_bluetooth_printer: ^2.3.0
  esc_pos_printer: ^4.1.0
  uuid: ^3.0.6
  restart_app:
  marquee: ^2.2.3
  widgets_to_image: ^0.0.2
  scrollable_positioned_list: ^0.3.8
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/svg/
    - assets/images/png/
